# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: detection.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x64\x65tection.proto\">\n\nInputImage\x12\x11\n\tbyteImage\x18\x01 \x01(\x0c\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x05\"N\n\x10\x44\x65tectionResults\x12\x15\n\rboundingBoxes\x18\x05 \x01(\x0c\x12\x11\n\tlandmarks\x18\x06 \x01(\x0c\x12\x10\n\x08numFaces\x18\x07 \x01(\x05\x32\x42\n\x10\x44\x65tectionService\x12.\n\ndetectFace\x12\x0b.InputImage\x1a\x11.DetectionResults\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'detection_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_INPUTIMAGE']._serialized_start=19
  _globals['_INPUTIMAGE']._serialized_end=81
  _globals['_DETECTIONRESULTS']._serialized_start=83
  _globals['_DETECTIONRESULTS']._serialized_end=161
  _globals['_DETECTIONSERVICE']._serialized_start=163
  _globals['_DETECTIONSERVICE']._serialized_end=229
# @@protoc_insertion_point(module_scope)
