# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import src.gRPCs.detection_pb2 as detection__pb2


class DetectionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.detectFace = channel.unary_unary(
                '/DetectionService/detectFace',
                request_serializer=detection__pb2.InputImage.SerializeToString,
                response_deserializer=detection__pb2.DetectionResults.FromString,
                )


class DetectionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def detectFace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DetectionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'detectFace': grpc.unary_unary_rpc_method_handler(
                    servicer.detectFace,
                    request_deserializer=detection__pb2.InputImage.FromString,
                    response_serializer=detection__pb2.DetectionResults.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DetectionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DetectionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def detectFace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DetectionService/detectFace',
            detection__pb2.InputImage.SerializeToString,
            detection__pb2.DetectionResults.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
