apiVersion: apps/v1
kind: Deployment
metadata:
  name: detector-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: detector-app
  template:
    metadata:
      labels:
        app: detector-app
    spec:
      containers:
      - name: detector-app
        image: detector-api:latest
        imagePullPolicy: Never
        resources:
          limits:
            memory: "2500Mi"
            cpu: "1500m"
        ports:
        - containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: detector-app
spec:
  type: NodePort
  selector:
    app: detector-app
  ports:
  - port: 50051
    targetPort: 50051
    nodePort: 30005